### ISSUE TITLE
No "PDF" Export option.

### ISSUE THREAD

**Issue by Jotynn** [garybentley/quollwriter#1]
For some reason the PDF export option is entirely absent from my export menu. I am unsure what is the issue.

**Comment by garybentley** [comment]
I was finding that the pdf export wasn't behaving correctly and took forever to do the wrong thing so I removed it.  I am looking for a replacement.  I would recommend exporting to a docx then convert to pdf via another program for now.

**Comment by Jotynn** [comment]
Ahhh, Good to know.
