### ISSUE TITLE
Warm up pop-up "start writing" button does not work using defaults.

### ISSUE THREAD

**Issue by KapFlagon** [garybentley/quollwriter#21]
# System details
Quoll Writer Version: 2.6.14
OS: Windows 10

# Steps to reproduce the issue:
1. Open Quoll Writer.
2. Either manually trigger a warm up exercise, or allow the automatic setting to trigger one.
3. The pop-up will display a writing prompt, and the "write your own prompt" field with some grey placeholder text. 
4. Without changing any settings, click the "start writing" button.
5. The pop-up does not respond, no matter how many times the button is clicked.
6. Click the field for writing your own prompt.
7. For a split second, the cursor will move to the end of the placeholder text, then back to the start of the field. 
8. Steps 6 and 7 can be repeated for as long as the placeholder text is shown in the "own prompt" field. 
9. While the "own prompt" field is still selected, click the "backspace" key on your keyboard.
10. The grey placeholder text will empty, and the field will now be completely blank.
11. Click the "Start writing" button.
12. The warm up will now begin with the auto-generated writing prompt. 

# Video
[QuollIssue.webm](https://user-images.githubusercontent.com/7314343/185498670-f1895e97-8123-47fc-a871-1bd29531ec97.webm)

# Ideal outcome of a fix
"Start Writing" button can be used using default data in the warm up pop-up. Placeholder "ghost" character does not need to be deleted before using the "Start Writing" button.

**Comment by garybentley** [comment]
Thanks for the detail and video.  I'm not going to be fixing this in version 2.6.xx.  With the move to version 3 I've already re-implemented the warm-up popup and I don't think it has the same problem.
